[build]
builder = "nixpacks"
buildCommand = "cd TodoListApi && dotnet restore && dotnet publish -c Release -o out"

[deploy]
startCommand = "cd TodoListApi/out && dotnet TodoListApi.dll"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3 