[build]
builder = "nixpacks"
buildCommand = "dotnet restore TodoListApi/TodoListApi.csproj && dotnet publish TodoListApi/TodoListApi.csproj -c Release -o out"

[deploy]
startCommand = "cd out && dotnet TodoListApi.dll"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3 